enum ModuleNames {
  Forum = 'forum',
  Quiz = 'quiz',
  Resource = 'resource',
  Glossary = 'glossary',
  Assign = 'assign',
  BigBlueButton = 'bigbluebuttonbn',
  Book = 'book',
  Chat = 'chat',
  choice = 'choice',
  Data = 'data',
  Feedback = 'feedback',
  Folder = 'folder',
  H5pactivity = 'h5pactivity',
  Imscp = 'imscp',
  Label = 'label',
  Lesson = 'lesson',
  Lti = 'lti',
  Page = 'page',
  Scorm = 'scorm',
  Survey = 'survery',
  Url = 'url',
  Wiki = 'wiki',
  Workshop = 'workshop',
}
export enum ModulePlurals {
  Forums = 'Forums',
  Quizzes = 'Quizzes',
  Files = 'Files',
}
export default ModuleNames;
